# Site settings
title: Data for Democracy
email: contact@datafordemocracy.org
description: > # this means to ignore newlines until "baseurl:"
  Data for Democracy is a community of data people volunteering on social impact projects.
url: 'https://d4d-preview.netlify.com/'
baseurl: '/'
twitter_username: data4democracy
github_username:  data4democracy

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"

plugins_dir:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
